//
//  AppKeys.h
//  myPota
//
//  Created by Rodrigo Pimentel on 08/05/14.
//  Copyright (c) 2014 web. All rights reserved.
//

//section table view para fazer o aparecer e desaparecer da view
//

#ifndef myPota_AppKeys_h
#define myPota_AppKeys_h

#pragma mark - StoryBoard Names

#define STORY_BOARD_CADASTRE_PERFIL         @"cadastrePotaToCodePota"
#define STORY_BOARD_CODE_PERFIL             @"codePOTA_perfilPOTA"
#define STORY_BOARD_CODE_LOGIN              @"codePotaToLoginPota"
#define STORY_BOARD_CODE_SEARCH             @"perfilPotaTobuscaPota"
#define STORY_BOARD_CODE_INVITE             @"cadastrePotaToInvitePota"
#define STORY_BOARD_LOGIN_PERFIL_AGENTE     @"loginPotaToAgentePerfilPota"
#define STORY_BOARD_PERFIL_AGENTE_MENU      @"potaPerfilAgenteTopotaMenu"
#define STORY_BOARD_SEARCH_CITY             @"searchPotaToStateCity"
#define STORY_BOARD_SEARCH_AGENCY           @"buscaPotaTochoiceAgencia"
#define STORY_BOARD_AGENCY_SELLER           @"choiceAgenciaTochoiceVendedor"
#define STORY_BOARD_SELLER_PERFIL           @"choiceVendedorToperfilPota"
#define STORY_BOARD_PERFIL_MENU             @"potaPerfilTopotaMenu"
#define STORY_BOARD_PERFIL_SEARCH           @"potaPerfilTopotaCadastro"
//MENU
#define STORY_BOARD_MENU_ASSISTENCIA        @"menuPotaToviagemPota"
#define STORY_BOARD_MENU_AGENTE_PERFIL      @"menuToAgentePerfil"
#define STORY_BOARD_MENU_PACOTES            @"menuPotaTopackgePota"
#define STORY_BOARD_MENU_HOTEL              @"menuPotaTomenuHotel"
#define STORY_BOARD_MENU_CARROS             @"menuPotaToperfilPota"
#define STORY_BOARD_MENU_TRANSLADOS         @"menuPotaToperfilPota"
#define STORY_BOARD_MENU_OPCIONAIS          @"menuPotaToperfilPota"
#define STORY_BOARD_MENU_INGRESSOS          @"menuPotaToperfilPota"
#define STORY_BOARD_MENU_VISTOS             @"menuPotaToperfilPota"
#define STORY_BOARD_MENU_PERFIL             @"menuPotaToperfilPota"
#define STORY_BOARD_MENU_CADASTRO           @"potaMenuTopotaCadastro"
//HOTEL
#define STORY_BOARD_HOTEL_ROOM              @"hotelPotaToroomPota"
#define STORY_BOARD_HOTEL_RESULT            @"hotelPotaToHotelPotaLista"
#define STORY_BOARD_HOTEL_INFO              @"hotelPotaListToHotelPotaInfo"
#define STORY_BOARD_HOTEL_CADASTRE          @"hotelPotaTocadastroPota"
#define STORY_BOARD_HOTEL_INFO_PICTURES     @"hotelInfoToPictureView"
#define STORY_BOARD_HOTEL_INFO_ROOMS        @"hotelPotaInfotoHotelPotaRoom"
#define STORY_BOARD_HOTEL_ROOMS_CADASTRE    @"hotelPotaRoomToCadastrePurchase"
//TRAVEL
#define STORY_BOARD_TRAVEL_TYPE             @"viagemPotaTotypePota"
#define STORY_BOARD_TRAVEL_DESTINY          @"viagemPotaTodestinyPota"
#define STORY_BOARD_TRAVEL_CALENDAR         @"viagemPotaTocalendarPota"
#define STORY_BOARD_TRAVEL_PLANOS           @"viagemPotaTotravelPackges"
#define STORY_BOARD_TRAVEL_INFO             @"travelPackgestravelInfo"
#define STORY_BOARD_TRAVEL_CADASTRE         @"travelPotaTocadastroPota"
//CADASTRO
#define STORY_BOARD_CADASTRE_INFO           @"cadastroPotaTocadastroInfoPota"
#define STORY_BOARD_CADASTRE_BUY            @"cadastrePotaTopurchasePota"
//BUY
#define STORY_BOARD_BUY_INFO                @"purchasePotaTocadastroInfoPota"
#define STORY_BOARD_BUY_VOLCHER             @"purchasePotaTovolcherPota"
//Voulcher
#define STORY_BOARD_MENU_VOLCHER            @"voulcherPotatomenuPota"
#define STORY_BOARD_VOUCHER_INFO            @"voucherPotaTocadastroInfoPota"
//PACKAGE
#define STORY_BOARD_PACK_TYPES_CIRCUIT       @"packgePotaTopackCircuit"
#define STORY_BOARD_PACK_CIRCUIT_INFO        @"packCircuitTopackInfo"
#define STORY_BOARD_PACK_CIRCUIT_INFO_DETAIL @"packInfoToDetail"
#define STORY_BOARD_PACK_INFO_PICTURES       @"packInfoToPictureView"
#define STORY_BOARD_PACK_INFO_DATA           @"packInfoToDataView"
#define STORY_BOARD_PACK_INFO_CITYS          @"packInfoToCitys"
#define STORY_BOARD_PACK_INFO_PURCHASE       @"packInfoToCadastrePurchase"


#pragma mark - ws key's

#define KEY_CODE_SITE                       @"4"
#define KEY_CODE_PORTAL                     @"1"
#define KEY_CODE_ACTION                     @"I"
#define KEY_CODE_STATUS                     @"P"
#define KEY_CODE_STATUS_PACKAGE             @"PR"
#define KEY_CODE_COUNTRY                    @"1"
#define KEY_BUY_TYPE                        @"CRE"
#define KEY_CODE_AGENCY                     @""
#define KEY_ACCESS_KEY                      @"appMobile"
#define KEY_TYPE_RETURN                     @"XML"
#define KEY_EMPTY                           @""
#define KEY_ID_WS                           @"TESTE_WS_SCHULTZ"
#define KEY_CODE_SITE_TRAVEL                @"1"
#define KEY_CODE_SITE_PACKAGE               @"4"
#define KEY_CODE_PORTAL_TRAVEL              @"1"
#define KEY_CODE_AREA_TRAVEL                @"4"
#define KEY_ID_WS_TRAVEL                    @"TESTE_WS_VITALCARD"
#define KEY_CODE_PRODUCT_TRAVEL             @"SEG"
#define KEY_CARD_MASTER                     @"MASTER"
#define KEY_CARD_VISA                       @"VISA"
#define KEY_CARD_AMEX                       @"AMEX"
#define KEY_CARD_DINER                      @"DINER"

#define CHAT_TYPE_SELLER @"VC"
#define CHAT_TYPE_USER   @"CV"

#pragma mark - plist's key

#define PLIST_STATE_NAME                    @"StatesData"
#define PLIST_STATE_TAG_SIGLAS              @"Siglas"
#define PLIST_STATE_TAG_NAMES               @"Names"
#define PLIST_STATE_TAG_CITYS               @"City"
#define PLIST_STATE_TAG_STATES              @"States"
#define PLIST_STATE_TAG_LOCAL               @"Local"
#define PLIST_STATE_TAG_SELLER              @"VendedorData"
#define PLIST_STATE_TAG_CHOSEN              @"Chosen"
#define PLIST_STATE_TAG_ROOM                @"room"
#define PLIST_STATE_TAG_ADULTS              @"Adults"
#define PLIST_STATE_TAG_CHILDREN            @"Children"
#define PLIST_STATE_TAG_AGES                @"Ages"
#define PLIST_HOTEL_NAME                    @"HotelSearchData"
#define PLIST_HOTEL_INFO_DESTINY            @"InfoDestiny"
#define PLIST_HOTEL_ID_CITY                 @"idCity"
#define PLIST_HOTEL_ID_COUNTRY              @"idCountry"
#define PLIST_HOTEL_NAME_CITY               @"nameCity"
#define PLIST_HOTEL_NAME_COUNTRY            @"nameCountry"
#define PLIST_HOTEL_NAME_STATE              @"nomeEstado"
#define PLIST_HOTEL_CITY_CODE               @"codigoCidade"
#define PLIST_HOTEL_CITY_NAME               @"nomeCidade"
#define PLIST_HOTEL_COUNTRY_CODE            @"codigoPais"
#define PLIST_HOTEL_COUNTRY_NAME            @"nomePais"
#define PLIST_ROOM_MENU                     @"RoomMenuLabels"
#define PLIST_HOTEL_ROOM_NAME               @"hotelPotaRoom"
#define PLIST_SELLER_NAME                   @"VendedorData"
#define PLIST_PURCHASES                     @"PurchaseList"

#define PLIST_NAME_CADASTRE                 @"cadastrePota"
#define CADASTRE_PLIST_KEY_ID               @"ID"
#define CADASTRE_PLIST_KEY_NAME             @"Nome"
#define CADASTRE_PLIST_KEY_LAST_NAME        @"SobreNome"
#define CADASTRE_PLIST_KEY_CPF              @"CPF"
#define CADASTRE_PLIST_KEY_RG               @"RG"
#define CADASTRE_PLIST_KEY_AGE              @"AGE"
#define CADASTRE_PLIST_KEY_ROOM             @"ROOM"
#define CADASTRE_PLIST_KEY_MAIL             @"MAIL"
#define CADASTRE_PLIST_KEY_FONE             @"FONE"
#define CADASTRE_PLIST_KEY_SEXO             @"SEXO"

#pragma mark - tag's navigation Bar

#define IMAGE_NAVIGATION_BAR_CLEAN          @"hudBarClear"
#define IMAGE_NAVIGATION_BAR_SEARCH         @"hudBarAgencia"
#define IMAGE_NAVIGATION_BAR_CITY           @"hudBarCidade"
#define IMAGE_NAVIGATION_BAR_STATE          @"hudBarEstado"
#define IMAGE_NAVIGATION_BAR_AGENCY         @"hudBarAgencia"
#define IMAGE_NAVIGATION_BAR_SELLER         @"hudBarVendedor"

#define IMAGE_NAVIGATION_BAR_PERFIL         @"navBarPota"
#define IMAGE_NAVIGATION_BAR_GENERIC        @"navBarGeneric"
#define IMAGE_NAVIGATION_BAR_VIAGEM         @"navBar02"
#define IMAGE_NAVIGATION_BAR_HOTEL          @"navBar03"
#define IMAGE_NAVIGATION_BAR_CALENDAR       @"navBar04"
#define IMAGE_NAVIGATION_BAR_PACKGE         @"navBar05"
#define IMAGE_NAVIGATION_BAR_RESERVA        @"navBar06"
#define IMAGE_NAVIGATION_BAR_PURCHASE       @"navBar07"
#define IMAGE_NAVIGATION_BAR_VOLCHER        @"navBar08"
#define IMAGE_NAVIGATION_BAR_PACKAGE        @"navBar09"
#define IMAGE_NAVIGATION_BAR_HOTEL_RESERVE  @"navBar10"
#define IMAGE_NAVIGATION_BAR_HOTEL_DETAILS  @"navBar11"
#define IMAGE_NAVIGATION_BAR_APP_VERSION     @"navBar12"

#define IMAGE_NAVIGATION_BAR_GEAR           @"hudBarMyPota"

#define IMAGE_NAVIGATION_BAR_VIAGEM_DADOS   @"hudBarMyPota"
#define IMAGE_NAVIGATION_BAR_VIAGEM_PACOTES @"hudBarMyPota"
#define IMAGE_NAVIGATION_BAR_HOTEL_CITY     @"navBarHotel"
#define IMAGE_NAVIGATION_BAR_HOTEL_RESULT   @"navBarHotel"
#define IMAGE_NAVIGATION_BAR_BUY            @"navBarHotel"
#define IMAGE_NAVIGATION_BAR_CADASTRE       @"hudBarMyPota"
#define IMAGE_NAVIGATION_BAR_BACK_BUTTON    @"btnBack"
#define NAVIGATION_BAR_BACK_TITLE_INIT      @"Início"
#define NAVIGATION_BAR_BACK_TITLE_BACK      @"Voltar"
#define NAVIGATION_BAR_BACK_TITLE_CLEAR     @""
#define NAVIGATION_BAR_BACK_TITLE_CALENDAR  @"Selecionar"

#pragma mark - string's

#define FONT_NAME                           @"HelveticaNeue"
#define FONT_NAME_BOLD                      @"HelveticaNeue-Bold"
#define FONT_NAME_MEDIUM                    @"HelveticaNeue-Medium"

#pragma mark - Travel Screen

#define TRAVEL_MAX_PEOPLE                   @"10"
#define SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(v)  ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] != NSOrderedAscending)
#define TRAVEL_MAX_PARCEL                   @"12"

#pragma mark - debug tags

#define DEBUG_TAG_SHOW_LINK_IN_CONNECTION   @"YES"

#pragma mark - connections labels

#define CODE_POTA_LABEL_CONNECTION_START                @"iniciando a conexão"
#define CODE_POTA_LABEL_CONNECTION_WAIT                 @"aguardando servidor"
#define CODE_POTA_LABEL_CONNECTION_RECIVE               @"recebendo dados"
#define CODE_POTA_LABEL_CONNECTION_FINISH               @"encerrando conexão"
#define CODE_POTA_LABEL_CONNECTION_ERROR                @"erro na conexão"

#define SEARCH_POTA_LABEL_CONNECTION_START_CITY         @"iniciando a conexão"
#define SEARCH_POTA_LABEL_CONNECTION_WAIT_CITY          @"aguardando servidor"
#define SEARCH_POTA_LABEL_CONNECTION_RECIVE_CITY        @"recebendo dados"
#define SEARCH_POTA_LABEL_CONNECTION_FINISH_CITY        @"encerrando conexão"
#define SEARCH_POTA_LABEL_CONNECTION_ERROR_CITY         @"erro na conexão"

#define SEARCH_POTA_LABEL_CONNECTION_START_AGENCY       @"iniciando a conexão"
#define SEARCH_POTA_LABEL_CONNECTION_WAIT_AGENCY        @"aguardando servidor"
#define SEARCH_POTA_LABEL_CONNECTION_RECIVE_AGENCY      @"recebendo dados"
#define SEARCH_POTA_LABEL_CONNECTION_FINISH_AGENCY      @"encerrando conexão"
#define SEARCH_POTA_LABEL_CONNECTION_ERROR_AGENCY       @"erro na conexão"

#define CHOICE_AGENCIA_LABEL_CONNECTION_START           @"iniciando a conexão"
#define CHOICE_AGENCIA_LABEL_CONNECTION_WAIT            @"aguardando servidor"
#define CHOICE_AGENCIA_LABEL_CONNECTION_RECIVE          @"recebendo dados"
#define CHOICE_AGENCIA_LABEL_CONNECTION_FINISH          @"encerrando conexão"
#define CHOICE_AGENCIA_LABEL_CONNECTION_ERROR           @"erro na conexão"

#define PERFIL_POTA_CONNECTION_START                    @"iniciando a conexão"
#define PERFIL_POTA_CONNECTION_WAIT                     @"aguardando servidor"
#define PERFIL_POTA_CONNECTION_RECIVE                   @"recebendo dados"
#define PERFIL_POTA_CONNECTION_FINISH                   @"encerrando conexão"
#define PERFIL_POTA_CONNECTION_ERROR                    @"erro na conexão"

#define TRAVEL_DESTINY_LABEL_CONNECTION_START           @"iniciando a conexão"
#define TRAVEL_DESTINY_LABEL_CONNECTION_WAIT            @"aguardando servidor"
#define TRAVEL_DESTINY_LABEL_CONNECTION_RECIVE          @"recebendo dados"
#define TRAVEL_DESTINY_LABEL_CONNECTION_FINISH          @"encerrando conexão"
#define TRAVEL_DESTINY_LABEL_CONNECTION_ERROR           @"erro na conexão"

#define TRAVEL_PACKGES_CONNECTION_START                 @"iniciando a conexão"
#define TRAVEL_PACKGES_CONNECTION_WAIT                  @"aguardando servidor"
#define TRAVEL_PACKGES_CONNECTION_RECIVE                @"recebendo dados"
#define TRAVEL_PACKGES_CONNECTION_FINISH                @"encerrando conexão"
#define TRAVEL_PACKGES_CONNECTION_ERROR                 @"erro na conexão"

#define TRAVEL_INFO_CONNECTION_START                    @"iniciando a conexão"
#define TRAVEL_INFO_CONNECTION_WAIT                     @"aguardando servidor"
#define TRAVEL_INFO_CONNECTION_RECIVE                   @"recebendo dados"
#define TRAVEL_INFO_CONNECTION_FINISH                   @"encerrando conexão"
#define TRAVEL_INFO_CONNECTION_ERROR                    @"erro na conexão"

#define HOTEL_POTA_CONNECTION_START                     @"iniciando a conexão"
#define HOTEL_POTA_CONNECTION_WAIT                      @"aguardando servidor"
#define HOTEL_POTA_CONNECTION_RECIVE                    @"recebendo dados"
#define HOTEL_POTA_CONNECTION_FINISH                    @"encerrando conexão"
#define HOTEL_POTA_CONNECTION_ERROR                     @"erro na conexão"

#define HOTEL_POTA_DESTINY_CONNECTION_START             @"iniciando a conexão"
#define HOTEL_POTA_DESTINY_CONNECTION_WAIT              @"aguardando servidor"
#define HOTEL_POTA_DESTINY_CONNECTION_RECIVE            @"recebendo dados"
#define HOTEL_POTA_DESTINY_CONNECTION_FINISH            @"encerrando conexão"
#define HOTEL_POTA_DESTINY_CONNECTION_ERROR             @"erro na conexão"

#define HOTEL_POTA_LIST_RESULT_CONNECTION_START         @"iniciando a conexão"
#define HOTEL_POTA_LIST_RESULT_CONNECTION_WAIT          @"aguardando servidor"
#define HOTEL_POTA_LIST_RESULT_CONNECTION_RECIVE        @"recebendo dados"
#define HOTEL_POTA_LIST_RESULT_CONNECTION_FINISH        @"encerrando conexão"
#define HOTEL_POTA_LIST_RESULT_CONNECTION_ERROR         @"erro na conexão"

#define BUY_POTA_CONNECTION_START                       @"iniciando a conexão"
#define BUY_POTA_CONNECTION_WAIT                        @"aguardando servidor"
#define BUY_POTA_CONNECTION_RECIVE                      @"recebendo dados"
#define BUY_POTA_CONNECTION_FINISH                      @"encerrando conexão"
#define BUY_POTA_CONNECTION_ERROR                       @"erro na conexão"

#define FACEBOOK_APP_CODE                               @"726624024043501"
#define FACEBOOK_APP_PERMS                              @[@"user_birthday",@"email"]
#define TRAVEL_MAX_DAY                                  120

#pragma mark - Purchase Travel Tag's

#define PURCHASE_DATA_TRAVEL_TYPE           @"Tipo_de_Viagem"
#define PURCHASE_DATA_TRAVEL_DESTINY        @"Destino"
#define PURCHASE_DATA_TRAVEL_DATA_START     @"Data_de_Saida"
#define PURCHASE_DATA_TRAVEL_DATA_END       @"Data_de_Retorno"
#define PURCHASE_DATA_TRAVEL_DAYS           @"Numero_de_dias"
#define PURCHASE_DATA_TRAVEL_PAX            @"Numero_de_Viajantes"
#define PURCHASE_DATA_TRAVEL_PAX_YOUNG      @"Numero_de_Viajantes_ate_75_anos"
#define PURCHASE_DATA_TRAVEL_PAX_OLD        @"Numero_de_Viajantes_>_de_75_anos"
#define PURCHASE_DATA_TRAVEL_LINK_PLAN      @"Link_dos_planos"
#define PURCHASE_DATA_TRAVEL_PLAN_SELECTED  @"InfoPlano"

#define PURCHASE_DATA_TRAVEL_INFO_PLAN_CODE         @"codigo"
#define PURCHASE_DATA_TRAVEL_INFO_PLAN_DESCRITION   @"descricao"
#define PURCHASE_DATA_TRAVEL_INFO_PLAN_NAME         @"nome"
#define PURCHASE_DATA_TRAVEL_INFO_PLAN_VALUE        @"valor"
#define PURCHASE_DATA_TRAVEL_INFO_PLAN_MAX_AGE      @"idadeMaxima"
#define PURCHASE_DATA_TRAVEL_INFO_PLAN_VALUE_SECURE @"valorSeguro"

#pragma mark - Purchase Type's
#define PURCHASE                            @"Purchase_Info"
#define PURCHASE_TYPE                       @"type"
#define PURCHASE_INFO_PRODUCT               @"Produto"
#define PURCHASE_INFO_SELLER                @"Vendedor"
#define PURCHASE_INFO_AGENCY                @"Agencia"
#define PURCHASE_TYPE_PERSON_DATA           @"Viajantes"
#define PURCHASE_INFO_BUDGET                @"Orcamento"
#define PURCHASE_INFO_PRODUCT_RESERVE       @"ReservaProduto"
#define PURCHASE_INFO_CARD                  @"CreditCard"
#define PURCHASE_INFO_VOLCHER               @"Volcher"
#define PURCHASE_INFO_PURCHASE_DETAILS      @"InfocoesDoProduto"
#define PURCHASE_INFO_PURCHASE_CONTRACT     @"InfocoesDoContrato"

#define CONTRATO_INFO_COD_SITE			 	@"COD_SITE"
#define CONTRATO_INFO_COD_PORTAL		 	@"COD_PORTAL"
#define CONTRATO_INFO_COD_FORNECEDOR	 	@"COD_FORNECEDOR"
#define CONTRATO_INFO_NOME_FORNECEDOR	 	@"NOME_FORNECEDOR"
#define CONTRATO_INFO_COD_PRODUTO 			@"COD_PRODUTO"
#define CONTRATO_INFO_COD_CONTRATO 			@"COD_CONTRATO"
#define CONTRATO_INFO_TIPO_CONTRATO_PRODUTO @"TIPO_CONTRATO_PRODUTO"
#define CONTRATO_INFO_TIPO_CONTRATO 		@"TIPO_CONTRATO"
#define CONTRATO_INFO_DESCRICAO 			@"DESCRICAO"

#define PURCHASE_TYPE_TRAVEL                @"Compra_de_Seguro"
#define PURCHASE_TYPE_HOTEL                 @"Compra_de_Hotel"
#define PURCHASE_TYPE_PACKGE                @"Compra_de_Pacote"

#define TAG_PACK_CIRCUIT                    @"Produto"
#define TAG_PACK_CIRCUIT_COIN               @"AbrMoeda"
#define TAG_PACK_CIRCUIT_COD_GROUP          @"CodGrupo"
#define TAG_PACK_CIRCUIT_COD_PRODUCT        @"CodProduto"
#define TAG_PACK_CIRCUIT_OPT_SELL           @"ComOpcoesVenda"
#define TAG_PACK_CIRCUIT_DSC_PERG           @"DscPergResp"
#define TAG_PACK_CIRCUIT_DSC_PLAN           @"DscPlano"
#define TAG_PACK_CIRCUIT_IND_AIR            @"IndAirOK"
#define TAG_PACK_CIRCUIT_IND_DESTAC         @"IndDestaque"
#define TAG_PACK_CIRCUIT_IND_PROMO          @"IndPromocao"
#define TAG_PACK_CIRCUIT_IND_SCREEN         @"IndTelaPrincipal"
#define TAG_PACK_CIRCUIT_NAME_GROUP         @"NomGrupo"
#define TAG_PACK_CIRCUIT_NAME_COUNTRY       @"NomPaisCidade"
#define TAG_PACK_CIRCUIT_NAME_PRODUCT       @"NomProduto"
#define TAG_PACK_CIRCUIT_NAME_SECURE        @"NomSeguradora"
#define TAG_PACK_CIRCUIT_NUM_DAYS           @"NumDias"
#define TAG_PACK_CIRCUIT_NUM_PARCELA        @"NumParcela"
#define TAG_PACK_CIRCUIT_NUM_RANK           @"NumRank"
#define TAG_PACK_CIRCUIT_SEO_DESCRIPTION    @"SeoDescricao"
#define TAG_PACK_CIRCUIT_TYPE_PRODUCT       @"TpoProduto"
#define TAG_PACK_CIRCUIT_TYPE_ROTEIRO       @"TpoRoteiro"
#define TAG_PACK_CIRCUIT_VALUE_ENTRADA      @"VlrEntrada"
#define TAG_PACK_CIRCUIT_VALUE_PARCELA      @"VlrParcela"
#define TAG_PACK_CIRCUIT_VALUE_VENDA        @"VlrVenda"
#define TAG_PACK_CIRCUIT_DATE_MES           @"dtaAnoMesDia"
#define TAG_PACK_CIRCUIT_DATE_PRODUTO       @"dtaProduto"
#define TAG_PACK_CIRCUIT_IMAGE_LOGO         @"imgLogoPeq"
#define TAG_PACK_CIRCUIT_IMAGE_PRODUTO      @"imgProduto"


#define CADASTRO_PERSON_FIRST_NAME  @"FirstName"
#define CADASTRO_PERSON_SECOND_NAME @"SecondName"
#define CADASTRO_PERSON_CPF         @"CPF"
#define CADASTRO_PERSON_GENDER      @"Gender"
#define CADASTRO_PERSON_AGE         @"Age"
#define CADASTRO_PERSON_MAIL        @"Mail"
#define CADASTRO_PERSON_FONE        @"Fone"
#define CADASTRO_PERSON_OBSERVER    @"Observer"
#define CADASTRO_PERSON_RECIVE_MAIL @"ReciveMail"
#define CADASTRO_PERSON_ROOM_TYPE   @"room_select"
#define CADASTRO_PERSON_HIDE        @"Hide"

#define PURCHASE_CARD_INFO_PACERLS  @"1"
#define PURCHASE_CARD_INFO_FLAG     @"CardFlag"
#define PURCHASE_CARD_INFO_NUMBER   @"CardNumber"
#define PURCHASE_CARD_INFO_COD      @"CardCod"
#define PURCHASE_CARD_INFO_MONTH    @"CardMonth"
#define PURCHASE_CARD_INFO_YEAR     @"CardYear"
#define PURCHASE_CARD_INFO_NAME     @"CardName"
#define PURCHASE_PERSON_INFO_ADRESS @"PurchaseAdress"
#define PURCHASE_PERSON_INFO_CITY   @"PurchaseCity"
#define PURCHASE_PERSON_INFO_UF     @"PurchaseUf"
#define PURCHASE_PERSON_INFO_CEP    @"PurchaseCep"
#define PURCHASE_PERSON_INFO_FONE   @"PurchaseFone"

#define USER_TYPE                   @"TipoDeUser"
#define USER_SELLER                 @"Seller"
#define USER_CLIENT                 @"Client"

#define AGENCY_DATA_URL_SITE     @"urlSiteAgenciaVendedor"
#define AGENCY_DATA_BAIRRO       @"bairroAgenciaVendedor"
#define AGENCY_DATA_CELULAR      @"celularAgenciaVendedor"
#define AGENCY_DATA_CODE         @"codigoAgenciaVendedor"
#define AGENCY_DATA_CODE_SITE    @"codigoSite"
#define AGENCY_DATA_COMPLEMENTO  @"complementoAgenciaVendedor"
#define AGENCY_DATA_CONTATO      @"contatoAgenciaVendedor"
#define AGENCY_DATA_DDD          @"dddAgenciaVendedor"
#define AGENCY_DATA_DDD_CELULAR  @"dddCelularAgenciaVendedor"
#define AGENCY_DATA_MAIL         @"emailAgenciaVendedor"
#define AGENCY_DATA_ADRESS       @"enderecoAgenciaVendedor"
#define AGENCY_DATA_FANTASY_NAME @"fantasiaAgenciaVendedor"
#define AGENCY_DATA_FONE         @"foneAgenciaVendedor"
#define AGENCY_DATA_IDWS         @"idWS"
#define AGENCY_DATA_IDWS_SITE    @"idWsSite"
#define AGENCY_DATA_LATITUDE     @"latitudeAgenciaVendedor"
#define AGENCY_DATA_LOGO         @"logoAgenciaVendedor"
#define AGENCY_DATA_LONGITUDE    @"longitudeAgenciaVendedor"
#define AGENCY_DATA_NAME         @"nomeAgenciaVendedor"
#define AGENCY_DATA_MUBER        @"numeroAgenciaVendedor"

#define SELLER_DATA_CITY         @"cidadeVendedor"
#define SELLER_DATA_CEP          @"cepAgenciaVendedor"
#define SELLER_DATA_CITY_CODE    @"codigoCidadeVendedor"
#define SELLER_DATA_CODE         @"codigoVendedor"
#define SELLER_DATA_DDD_CELULAR  @"dddCelularVendedor"
#define SELLER_DATA_DDD          @"dddVendedor"
#define SELLER_DATA_MAIL         @"emailVendedor"
#define SELLER_DATA_FACE         @"facebookVendedor"
#define SELLER_DATA_FONE_CELULAR @"foneCelularVendedor"
#define SELLER_DATA_FONE         @"foneVendedor"
#define SELLER_DATA_FOTO         @"fotoVendedor"
#define SELLER_DATA_GTALK        @"gtalkVendedor"
#define SELLER_DATA_UF_NAME      @"nomeUfVendedor"
#define SELLER_DATA_NAME         @"nomeVendedor"
#define SELLER_DATA_GENDER       @"sexoVendedor"
#define SELLER_DATA_UF           @"siglaUfVendedor"
#define SELLER_DATA_SKYPE        @"skypeVendedor"
#define SELLER_DATA_TWIITER      @"twitterVendedor"
#define SELLER_DATA_WHATSAPP     @"whatsupVendedor"

#define PACKAGE_INFO_DATA                     @"PackageData"
#define PACKAGE_INFO_TYPE                     @"PackageTipo"
#define PACKAGE_INFO_CIRCUIT                  @"PackageCircuitos"
#define PACKAGE_INFO_DETAIL                   @"PackageInfo"
#define PACKAGE_INFO_PRICE                    @"PackagePrice"
#define PACKAGE_INFO_ROOM_SIZE                @"PackageRoomSize"
#define PACKAGE_INFO_ROOM_INFO                @"PackageRoomInfo"
#define PACKAGE_INFO_ROOM_NAME                @"PackageRoomName"
#define PACKAGE_INFO_ROOM_NUMBER              @"PackageRoomNumber"
#define PACKAGE_INFO_ROOM_PRICE               @"PackageRoomPrice"
#define PACKAGE_INFO_HTML_DATA                @"htmlData"
#define PACKAGE_INFO_HTML_GENERAL_CONDICTIONS @"htmlGeneralConditions"
#define PACKAGE_INFO_HTML_IS_INCLUDE          @"htmlIsInclude"
#define PACKAGE_INFO_HTML_DAY_FOR_DAY         @"htmlDayForDay"

//WS GET DATA FOR PACKAGE
#define PACKAGE_INFO_DATA_SEARCH_COD_PLAN 			@"CodPlano"
#define PACKAGE_INFO_DATA_SEARCH_COD_TEMP 			@"CodTemporada"
#define PACKAGE_INFO_DATA_SEARCH_COD_TYPE_TEMP 		@"CodTipoTemporada"
#define PACKAGE_INFO_DATA_SEARCH_IND_AERO			@"IndAereo"
#define PACKAGE_INFO_DATA_SEARCH_COD_PLAN_AERO		@"CodPlanoAereo"
#define PACKAGE_INFO_DATA_SEARCH_DATA_ORIGINAL	  	@"DtaOriginal"
#define PACKAGE_INFO_DATA_SEARCH_DATA_FORMATED	 	@"DtaFormatada"
#define PACKAGE_INFO_DATA_SEARCH_DATA_AERO			@"DtaAereo"
#define PACKAGE_INFO_DATA_SEARCH_COD_TYPE_CIRCUIT	@"CodEuropamundo"
#define PACKAGE_INFO_DATA_SEARCH_DATA_FORMATED_WS   @"DtaFormatadaWS"
#define PACKAGE_INFO_DATA_SEARCH_DSC_TYPE_TEMP	 	@"DscTipoTemporada"
#define PACKAGE_INFO_DATA_SEARCH_IND_PER_SOL_RES	@"IndPermitirSolicReserva"
#define PACKAGE_INFO_DATA_SEARCH_COMB_OPT_SELLING 	@"CombinacaoOpcoesVenda"
#define PACKAGE_INFO_DATA_SEARCH_DATA_EXTENCE		@"DtaExtenso"
#define PACKAGE_INFO_DATA_SEARCH_DATA_EXTENCE_AERO	@"DtaExtensoAereo"
#define PACKAGE_INFO_DATA_SEARCH_MONTH_AJUST 		@"MesAjustado"
#define PACKAGE_INFO_DATA_SEARCH_YEAR_AJUST  		@"AnoAjustado"
#define PACKAGE_INFO_DATA_SEARCH_MONTH_ORG   		@"MesOriginal"
#define PACKAGE_INFO_DATA_SEARCH_YEAR_ORG		 	@"AnoOriginal"
#define PACKAGE_INFO_DATA_SEARCH_TYPE_PRODUCT		@"TpoProduto"
#define PACKAGE_INFO_DATA_SEARCH_TYPE_ROTEIRO		@"TpoRoteiro"
#define PACKAGE_INFO_DATA_SEARCH_QUANT_DISP 		@"QtdDisponivel"
#define PACKAGE_INFO_DATA_SEARCH_QUANT_DISP_AERO 	@"QtdDisponivelAereo"
#define PACKAGE_INFO_DATA_SEARCH_QUANT_DISP_CRUZERO @"QtdDisponivelCruzeiro"
#define PACKAGE_INFO_DATA_SEARCH_DATA_ATIVA		 	@"DtaAtiva"
#define PACKAGE_INFO_DATA_SEARCH_DATA_ATIVA_AERO	@"DtaAtivaAereo"
#define PACKAGE_INFO_DATA_SEARCH_TYPE_AERO		 	@"TpoAereo"

//WS GET ROONS FOR PACKAGE
#define PACKAGE_INFO_DATA_SEARCH_ROOM_ABR_COIN 				 @"AbrMoeda"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DAYS_LAST_AERO 		 @"DiasAnteriorAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DAYS_POST_AERO 		 @"DiasPosteriorAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_TAXA 			     @"DscTaxa"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_TAXA_AERO 		 @"DscTaxaAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_TAXA_CRUZ 		 @"DscTaxaCruz"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_TAXA_PRAZO 		 @"DscTaxaPrazo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_TAXA_PRAZO_AERO 	 @"DscTaxaPrazoAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_TAXA_PRAZO_CRUZ 	 @"DscTaxaPrazoCruz"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_TYPE_ACOMODATION 	 @"DscTpoAcomodacao"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_DSC_VALUE_PLAN		 @"DscVlrPlano"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_IND_COMPAR 			 @"IndCompartir"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_IND_PACKAGE 			 @"IndPacote"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_NIGHT_END 			 @"NoiteBordoFim"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_NIGHT_START 			 @"NoiteBordoIni"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_ORD_PRODUCT			 @"OrdemProduto"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_QTD_NIGHT_EXTRA_END 	 @"QtdNoiteExtraFim"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_QTD_NIGHT_EXTRA_START  @"QtdNoiteExtraIni"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_QTD_PEOPLE			 @"QtdPessoas"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_SEQ_VALUE_PLAN	     @"SeqVlrPlano"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_SGL_ACOMODATION 		 @"SglAcomodacao"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_SGL_COIN 		  		 @"SglMoeda"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_TOT_TAXA 		 		 @"TotTaxa"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_TYPE_AERO 	 		 @"TpoAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_TYPE_PRODUCT	 		 @"TpoProduto"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_TYPE_ROTEIRO	 		 @"TpoRoteiro"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_AERO 			 @"VlrAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_CRUZ 			 @"VlrCruz"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_TAXA 			 @"VlrTaxa"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_TAXA_AERO 		 @"VlrTaxaAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_TAXA_CRUZ 		 @"VlrTaxaCruz"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_TAXA_PRAZO 		 @"VlrTaxaPrazo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_TAXA_PRAZO_AERO  @"VlrTaxaPrazoAereo"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_TAXA_PRAZO_CRUZ  @"VlrTaxaPrazoCruz"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_VALUE_VALUE_VENDA		 @"VlrVenda"
#define PACKAGE_INFO_DATA_SEARCH_ROOM_NAME_HOTEL             @"DscAcomodacao"

//hotel
#define MAX_PEOPLE_HOTEL        4
#define MAX_PEOPLE_HOTEL_CHILDS 2
#define MAX_NUMBER_HOTEL_ROOMS  4

#define HOTEL_INFO_DESTINY           @"Destino"
#define HOTEL_INFO_NUMBER_ADULTS     @"Numero_de_adultos"
#define HOTEL_INFO_NUMBER_CHILDRENS  @"Numero_de_criancas"
#define HOTEL_INFO_NUMBER_TRAVELLER  @"Numero_de_viajantes"
#define HOTEL_INFO_AGE_CHILDRENS     @"Idade_das_criancas"
#define HOTEL_INFO_NUMBER_ROONS      @"Numero_de_quartos"
#define HOTEL_INFO_DATA_GO           @"Data_saida"
#define HOTEL_INFO_DATA_END          @"Data_retorno"
#define HOTEL_INFO_NUMBER_NIGHTS     @"Data_total"
#define HOTEL_CALENDAR_GO_NUMERIC    @"data_de_saida_numerica"
#define HOTEL_CALENDAR_END_NUMERIC   @"data_de_retorno_numerica"
#define HOTEL_CALENDAR_GO_ALPHA      @"data_de_saida_extenca"
#define HOTEL_CALENDAR_END_ALPHA     @"data_de_retorno_extenca"
#define HOTEL_LINK_WS_INFO           @"wsInfo"
#define HOTEL_LINK_WS_TOKEN          @"wsToken"
#define HOTEL_LINK_WS_COUNTER        @"wsCounter"
#define HOTEL_LINK_WS_FINAL          @"wsFinal"
#define HOTEL_LINK_WS_COD_SITE       @"wsCodSite"
#define HOTEL_INFO_ALL               @"info_all_Hotel"
#define HOTEL_INFO                   @"infoHotel"

#endif